# Generated by Django 5.2.6 on 2025-10-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article'),
            preserve_default=False,
        ),
    ]
